steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Build Next.js application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NEXT_PUBLIC_ANALYZE_IMAGE_URL=${_ANALYZE_IMAGE_URL}'
      - 'NEXT_PUBLIC_ANALYZE_VIDEO_URL=${_ANALYZE_VIDEO_URL}'
      - 'NEXT_PUBLIC_VIDEO_ANALYSIS_URL=${_VIDEO_ANALYSIS_URL}'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/visionbridge:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/visionbridge:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'visionbridge'
      - '--image'
      - 'gcr.io/$PROJECT_ID/visionbridge:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_ANALYZE_IMAGE_URL=${_ANALYZE_IMAGE_URL},NEXT_PUBLIC_ANALYZE_VIDEO_URL=${_ANALYZE_VIDEO_URL},NEXT_PUBLIC_VIDEO_ANALYSIS_URL=${_VIDEO_ANALYSIS_URL}'
      - '--set-secrets'
      - 'yuting=yuting:latest'
      
images:
  - 'gcr.io/$PROJECT_ID/visionbridge:$COMMIT_SHA'

substitutions:
  _ANALYZE_IMAGE_URL: 'https://asia-northeast1-visionbridge.cloudfunctions.net/analyzeImage'
  _ANALYZE_VIDEO_URL: 'https://asia-northeast1-visionbridge.cloudfunctions.net/analyzeVideo'
  _VIDEO_ANALYSIS_URL: 'https://asia-northeast1-visionbridge.cloudfunctions.net/videoAnalysis'
